# Generated by Django 4.2.1 on 2023-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.IntegerField(default=0)),
                ('generacion', models.CharField(default='', max_length=25)),
                ('tipo', models.CharField(max_length=8)),
            ],
        ),
    ]
